#!/usr/bin/env bash

function delayedPluginInstall {
    sudo mkdir -p /home/developer/.IdeaIC2016.1/config/plugins
    sudo mkdir -p /home/developer/.IdeaIC2016.1/config/options
    sudo chown developer:developer -R /home/developer/.IdeaIC2016.1

    cd /home/developer/.IdeaIC2016.1/config/plugins/

    echo 'Installing Scala plugin'
    wget https://plugins.jetbrains.com/files/1347/26538/scala-intellij-bin-3.0.8.zip -O cala.zip -q && unzip -q scala.zip && rm scala.zip

    # Adding the predefined preferences to IDEA
    cp /home/developer/.jdk.table.xml /home/developer/.IdeaIC2016.1/config/options/jdk.table.xml
}

if [ ! -d /home/developer/.IdeaIC2016.1/config/plugins/Scala ]; then
    # We are running with a non-Docker contained volume for IntelliJ prefs so we need to setup the plugin again
    delayedPluginInstall
fi

if [ -d /home/developer/.IdeaIC2016.1 ]; then
    # Ensure proper permissions
    sudo chown developer:developer -R /home/developer/.IdeaIC2016.1
fi

exec /opt/intellij/bin/idea.sh